pluginManagement {
	repositories {
		gradlePluginPortal()
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'Jitpack'
			url = 'https://jitpack.io'
		}
		maven {
			name = 'Babric'
			url = 'https://maven.glass-launcher.net/babric'
		}
		maven {
			name = 'SignalumMavenInfrastructure'
			url = 'https://maven.thesignalumproject.net/infrastructure'
		}
	}
	plugins {
		id 'org.jetbrains.kotlin.jvm' version '2.1.0'
	}
}
plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

include ':catalyst-core'
project(":catalyst-core").projectDir = file("${rootProject.projectDir}/core")
include ':catalyst-energy'
project(":catalyst-energy").projectDir = file("${rootProject.projectDir}/energy")
include ':catalyst-fluids'
project(":catalyst-fluids").projectDir = file("${rootProject.projectDir}/fluids")
include ':catalyst-multiblocks'
project(":catalyst-multiblocks").projectDir = file("${rootProject.projectDir}/multiblocks")
include ':catalyst-multipart'
project(":catalyst-multipart").projectDir = file("${rootProject.projectDir}/multipart")
include ':catalyst-effects'
project(":catalyst-effects").projectDir = file("${rootProject.projectDir}/effects")
